name = "boostr3" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "boostr3.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.boostr3.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.boostr3.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "www.sushiroll.co.id.boostr3.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "blog.sushiroll.co.id.boostr3.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "cdn.appsflyer.com.boostr3.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.boostr3.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.boostr3.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "www.joox.com.boostr3.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.staging.vidio.com.boostr3.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "zoomcares.zoom.us.boostr3.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "graph.facebook.com.boostr3.fadzvpnproject.xyz"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "b3bf7776-0451-4ab1-afb6-0f21ef63ddc2"
