name = "serversg" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "support.zoom.us.serversg.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "beta.zoom.us.serversg.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "englishtest-stage-7.duolingo.com.serversg.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "104.18.17.230.serversg.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "support.duolingo.com.serversg.fadzvpnid.filegear-sg.me"
custom_domain = true
pattern = "quiz.int.vidio.com.serversg.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "quiz.staging.vidio.com.serversg.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.serversg.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "Ava.game.naver.com.serversg.fadzvpnid.filegear-sg.me"
custom_domain = true
pattern = "Df.game.naver.com.serversg.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.serversg.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "cdn.appsflyer.com.serversg.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "www.pubgmobile.com.serversg.fadzvpnid.filegear-sg.me"
custom_domain = true



[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "9309b805-49fc-40f0-9591-1fb7b1948274"
