name = "idfadz" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "idfadz.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.idfadz.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "blog.sushiroll.co.id.idfadz.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.idfadz.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "www.sushiroll.co.id.idfadz.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "app.gopay.co.id.idfadz.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.idfadz.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "investor.spotify.com.idfadz.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "cdn.appsflyer.com.idfadz.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "graph.facebook.com.idfadz.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "104.26.6.171.idfadz.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "app.genflix.co.id.idfadz.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "104.18.20.226.idfadz.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "chat.sociomile.com.idfadz.fadztunnell.my.id"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "9309b805-49fc-40f0-9591-1fb7b1948274"
