name = "sgdo" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "www.sushiroll.co.id.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "blog.sushiroll.co.id.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "cdn.appsflyer.com.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "investor.spotify.com.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "www.joox.com.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "quiz.staging.vidio.com.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "zoomcares.zoom.us.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "graph.facebook.com.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "www.help.tinder.com.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "104.16.51.111.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "poe.garena.com.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "games.axis.co.id.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "api.ovo.id.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "www.udemy.com.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "104.26.6.171.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "app.gopay.co.id.sgdo.tunneltech.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "go.appsflyer.com.sgdo.tunneltech.filegear-sg.me"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "9309b805-49fc-40f0-9591-1fb7b1948274"
