name = "javhd" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "Ava.game.naver.com.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "Df.game.naver.com.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "Graph.facebook.com.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "v27.tiktokcdn.com.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "englishtest-stage-7.duolingo.com.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "api.zoom.us.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "Account.pmang.game.naver.com.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "support.duolingo.com.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "static.cdninstagram.com.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "www.pubgmobile.com.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "www.sushiroll.co.id.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "games.axis.co.id.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "cdn.appsflyer.com.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "cftxvid.vod.nimo.tv.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "connect.garenanow.com.javhd.fadzvpnid.filegear-sg.me"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "9309b805-49fc-40f0-9591-1fb7b1948274"
