name = "boostr2" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "www.sushiroll.co.id.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "blog.sushiroll.co.id.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "cdn.appsflyer.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "www.joox.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.staging.vidio.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "zoomcares.zoom.us.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "graph.facebook.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "www.help.tinder.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "poe.garena.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "games.axis.co.id.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "api.ovo.id.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "cdnodeb.visionplus.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "104.26.6.171.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "app.gopay.co.id.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "go.appsflyer.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "devsupport.webex.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "edu.ruangguru.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "fadz.ngapaktunnelling.xyz.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "creativeservices.netflix.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "npca.netflix.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "gw.ruangguru.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "edu.udemy.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "104.16.51.111.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "web.poe.garena.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "static.cdninstagram.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "dl.cvs.freefiremobile.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "104.17.74.206.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "104.17.3.81.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "sogood.linefriends.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "104.18.29.141.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "layanan.ruangguru.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "104.16.51.111.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "help.pornhub.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "162.159.130.11.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "162.159.138.6.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "web.poe.garena.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "s.youtube.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "m.pubgmobile.com .boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "app.genflix.co.id.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "mssdk24-normal-useast2a.tiktokv.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "lipcon.com.boostr2.fadzvpnproject.xyz"
custom_domain = true
[[routes]]
pattern = "edge-ig-mqtt-p4-shv-01-dub4.facebook.com.boostr2.fadzvpnproject.xyz"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "b3bf7776-0451-4ab1-afb6-0f21ef63ddc2"
